### ISSUE TITLE
Polyak Averaging Params_ema initiailzation

### ISSUE THREAD

**Issue by joaogui1** [google-research/flax#13]
Hi, I was applying the changes in your HOWTO to add Polyak averaging and there seems to be some code missing, specifically params_ema is not initialized and so the line 
`optimizer, params_ema = train_step(optimizer, params_ema, batch)`
causes an UnboundLocalError (params_ema referenced before assignment).

**Comment by avital** [comment]
Yes you're right. Want to file a CL?

**Comment by avital** [comment]
Er, I meant a PR :)

**Comment by joaogui1** [comment]
Okss, will try

**Comment by joaogui1** [comment]
Done! @avital

**Comment by avital** [comment]
@marcvanzee is in the process of changing the example diff in the README and putting up our HOWTOs in a more structured way, so I'm closing this for now. Thanks @joaogui1!
