### ISSUE TITLE
Incorrext init for LSTM

### ISSUE THREAD

**Issue by david-waterworth** [google-research/flax#17]
The code below appears incorrect - I may be misunderstanding though. As per the comment you're summing 2 dense layers so one has no bias - but dense_h has bias=False and you're passing the bias_init, dense_i has `bias=True` but is using the default bias_init? Should be the other way around or pass bias_init to both?

Since the default bias_init is zeros for both Dense.apply() and LSTMCell.apply() it has no impact unless a different bias_init is supplied?

https://github.com/google-research/flax/blob/e7247d58e4f3460c03da5f935cb83d9c0883a97c/flax/nn/recurrent.py#L97-L103

**Comment by jheek** [comment]
You are right bias_init should be passed to dense_i instead. Do you want to make a PR?

**Comment by david-waterworth** [comment]
I submitted https://github.com/google-research/flax/pull/18

**Comment by avital** [comment]
#18 was merged, so I'll close this. Thanks!
